#pragma once

//DDNet

enum
{
	DDNET_PLAYERFLAG_AIM = 1 << 4,

	DDNET_NETMSGTYPE_CL_DDNETVERSION = 26,

	VERSION_VANILLA = 0,
	VERSION_DDRACE = 1,
	VERSION_DDNET_OLD = 2,
	VERSION_DDNET_WHISPER = 217,
	VERSION_DDNET_GOODHOOK = 221,
	VERSION_DDNET_EXTRATUNES = 302,
	VERSION_DDNET_RCONPROTECT = 408,
	VERSION_DDNET_ANTIPING_PROJECTILE = 604,
	VERSION_DDNET_HOOKDURATION_TUNE = 607,
	VERSION_DDNET_FIREDELAY_TUNE = 701,
	VERSION_DDNET_UPDATER_FIXED = 707,
	VERSION_DDNET_GAMETICK = 10042,
};